//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Actor
    {
        public int Id { get; set; }
        [MaxLength(20, ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "TooLongUserName")]
        [Required(ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "EmptyUserError")]
        public string UserName { get; set; }
        [MaxLength(20, ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "TooLongPassword")]
        [Required(ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "EmptyPasswordError")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
