//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Entities
{
    using StudentManagement.Entities.Validators;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int Id { get; set; }
        [Display(Name = "First Name")]
        [StringLength(25, ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "TooLongFirstName")]
        [Required(ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "EmptyStudentName")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        [StringLength(25, ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "TooLongLastName")]
        [Required(ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "EmptyStudentLast")]
        public string LastName { get; set; }
        [Display(Name = "Phone")]
        [StringLength(30, ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "TooLongPhoneNumber")]
        [ValidPhone(ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "InvalidPhoneFormat")]
        [Required(ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "EmptyStudentPhone")]
        public string PhoneNumber { get; set; }
        [Display(Name = "Birthday")]
        [MinimumAge(18, ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "StudentTooYoung")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "EmptyStudentBirthday")]
        public System.DateTime Birthday { get; set; }
        [Display(Name = "Nicknames")]
        [StringLength(250, ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "TooLongNicknames")]
        public string NickNames { get; set; }
        [Display(Name = "Student No.")]
        [StringLength(50)]
        public string StudentNumber { get; set; }
        [Display(Name = "Email")]
        [StringLength(50, ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "TooLongEmailError")]
        [Required(ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "EmptyStudentEmail")]
        [EmailAddress(ErrorMessageResourceType = typeof(Resources.MessageResource), ErrorMessageResourceName = "InvalidEmailFormat")]
        public string Email { get; set; }
    }
}
